[package]
name = "bevy_uni-app"
version = "0.1.0"
authors = ["Tomasz Sterna <tomek@sterna.link>"]
edition = "2018"

[dependencies]
bevy = { git = "https://github.com/bevyengine/bevy", default-features = false }
uni-app = "0.1.3"
log = "0.4"
